./bhsparse -cuda -spgemm MTX/filter3D/filter3D.mtx MTX/filter3D/filter3D.mtx
./bhsparse -cuda -spgemm MTX/shipsec1/shipsec1.mtx  MTX/shipsec1/shipsec1.mtx
./bhsparse -cuda -spgemm MTX/harbor/harbor.mtx  MTX/harbor/harbor.mtx
./bhsparse -cuda -spgemm MTX/pdb1HYS/pdb1HYS.mtx  MTX/pdb1HYS/pdb1HYS.mtx
./bhsparse -cuda -spgemm MTX/consph/consph.mtx MTX/consph/consph.mtx
./bhsparse -cuda -spgemm MTX/2cubes_sphere/2cubes_sphere.mtx MTX/2cubes_sphere/2cubes_sphere.mtx
./bhsparse -cuda -spgemm MTX/cop20k_A/cop20k_A.mtx MTX/cop20k_A/cop20k_A.mtx
./bhsparse -cuda -spgemm MTX/cage12/cage12.mtx MTX/cage12/cage12.mtx
./bhsparse -cuda -spgemm MTX/hood/hood.mtx MTX/hood/hood.mtx
./bhsparse -cuda -spgemm MTX/m133-b3/m133-b3.mtx MTX/m133-b3/m133-b3.mtx
./bhsparse -cuda -spgemm MTX/majorbasis/majorbasis.mtx MTX/majorbasis/majorbasis.mtx
./bhsparse -cuda -spgemm MTX/mario002/mario002.mtx MTX/mario002/mario002.mtx
./bhsparse -cuda -spgemm MTX/offshore/offshore.mtx  MTX/offshore/offshore.mtx
./bhsparse -cuda -spgemm MTX/patents_main/patents_main.mtx  MTX/patents_main/patents_main.mtx
./bhsparse -cuda -spgemm MTX/poisson3Da/poisson3Da.mtx  MTX/poisson3Da/poisson3Da.mtx
./bhsparse -cuda -spgemm MTX/scircuit/scircuit.mtx  MTX/scircuit/scircuit.mtx
./bhsparse -cuda -spgemm MTX/power197k/power197k.mtx  MTX/power197k/power197k.mtx
./bhsparse -cuda -spgemm MTX/youtube/youtube.mtx  MTX/youtube/youtube.mtx
./bhsparse -cuda -spgemm MTX/as-cida/as-cida.mtx  MTX/as-cida/as-cida.mtx
./bhsparse -cuda -spgemm MTX/mathoverflow/mathoverflow.mtx  MTX/mathoverflow/mathoverflow.mtx
./bhsparse -cuda -spgemm MTX/loc-gowalla/loc-gowalla.mtx  MTX/loc-gowalla/loc-gowalla.mtx
./bhsparse -cuda -spgemm MTX/emailEnron/emailEnron.mtx  MTX/emailEnron/emailEnron.mtx
./bhsparse -cuda -spgemm MTX/slashDot/slashDot.mtx MTX/slashDot/slashDot.mtx
./bhsparse -cuda -spgemm MTX/epinions/epinions.mtx MTX/epinions/epinions.mtx
./bhsparse -cuda -spgemm MTX/web-NotreDame/web-NotreDame.mtx MTX/web-NotreDame/web-NotreDame.mtx
./bhsparse -cuda -spgemm MTX/stanford/stanford.mtx  MTX/stanford/stanford.mtx
